### ISSUE TITLE
DMGs content not appearing

### ISSUE THREAD

**Issue by big610** [pretty-clean/pretty-clean.github.io#4]
DMGs content main-screen option in 0.118, missing/not appearing in 0.127. Is an extremely helpful feature.
Left side, Downloads 0.127 has the exact same size as DMGs 0.118, but does not appear like 0.118.
Can you please fix, re-add?

In addition, please publish Release Notes.
Then we have a full understanding what has been done. Helpful for troubleshooting, testing, features added/removed.  Thank you.

**Comment by aiyanbo** [comment]
@big610 Thanks for reaching out, we are improving your ideas.

**Comment by aiyanbo** [comment]
@big610 We moved the DMGs list to the downloads category. You can click the `Downloads` item to view them.
