### ISSUE TITLE
uninstaller Not available

### ISSUE THREAD

**Issue by Zanetach** [pretty-clean/pretty-clean.github.io#5]
version：0.1.28-beta4 @ aarch64
<img width="1229" alt="image" src="https://user-images.githubusercontent.com/60311214/215239647-b62e14c6-7db8-4a3b-8762-d32d0b934670.png">

<img width="1229" alt="image" src="https://user-images.githubusercontent.com/60311214/215239559-4db0c915-2a89-4305-8bd0-30d42c8a8eec.png">

**Comment by aiyanbo** [comment]
您的系统版本号是多少？可能需要在系统设置里面授权一下 “完全访问”。

**Comment by Zanetach** [comment]
MacOS . 13.1 (22C65)
在哪里设置完全访问呢？
<img width="1240" alt="image" src="https://user-images.githubusercontent.com/60311214/215253522-5203ab44-5dc4-448a-af88-999635ebd54b.png">

**Comment by Zanetach** [comment]
已设置 完全访问
<img width="532" alt="image" src="https://user-images.githubusercontent.com/60311214/215256183-4a05a99d-b098-432a-8700-204809a86467.png">

**Comment by aiyanbo** [comment]
大概是加载某个软件时出错了，导致列表没有出来。我加个错误信息看一下，您稍等。

**Comment by Zanetach** [comment]
有什么好方法解决么？

我的是Macbook air m2

**Comment by aiyanbo** [comment]
@Hugo-Hsiao 我找到了一个疑似有 bug 的加载逻辑，并发布了 beta6 版本，您看一下这个问题是否还存在？或者您方便提供 WeChat 吗？我加您，方便后面的沟通。

**Comment by aiyanbo** [comment]
更新的两种方式：
1. 在应用中点击 “设置” -> “关于 PrettyClean” -> "Check for updates"
2. 访问 https://www.prettyclean.cc/beta 点击下载

**Comment by Hugo-Hsiao** [comment]
WeChat Hugo-0706

**Comment by Hugo-Hsiao** [comment]
> @Hugo-Hsiao 我找到了一个疑似有 bug 的加载逻辑，并发布了 beta6 版本，您看一下这个问题是否还存在？或者您方便提供 WeChat 吗？我加您，方便后面的沟通。

@aiyanbo WeChat ID：Hugo-0706

**Comment by Zanetach** [comment]
> 

<img width="1237" alt="image" src="https://user-images.githubusercontent.com/60311214/215317139-cf7bcc55-c590-4527-ad5d-6a3e9427bbb8.png">

app 还是不能加载出来
@aiyanbo

**Comment by aiyanbo** [comment]
Fixed in 0.1.31
